[server]
runOnSave = true

[global]
enableCORS = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server.environment]
GEMINI_API_KEY = "AIzaSyCE95wGJhcj84fQtx4doY-qLD_7nKO4eXE"
